apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: simple-web
  description: "Una aplicación web simple y elegante que consume APIs públicas para mostrar datos dinámicos"
  tags:
    - javascript
    - html
    - css
    - api-consumer
    - frontend
    - responsive
  annotations:
    github.com/project-slug: jplacenciaf/simple-web
    backstage.io/source-location: url:https://github.com/jplacenciaf/simple-web
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: production
  owner: jplacenciaf
  system: web-applications
  providesApis: []
  consumesApis:
    - jsonplaceholder-api
    - quotable-api
  dependsOn: []

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: jsonplaceholder-api
  description: "API externa para obtener datos de usuarios y posts"
spec:
  type: openapi
  lifecycle: production
  owner: external
  system: external-apis
  definition: |
    openapi: 3.0.0
    info:
      title: JSONPlaceholder API
      version: 1.0.0
    servers:
      - url: https://jsonplaceholder.typicode.com
    paths:
      /users:
        get:
          summary: Get all users
      /posts:
        get:
          summary: Get all posts

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: quotable-api
  description: "API externa para obtener citas inspiracionales aleatorias"
spec:
  type: openapi
  lifecycle: production
  owner: external
  system: external-apis
  definition: |
    openapi: 3.0.0
    info:
      title: Quotable API
      version: 1.0.0
    servers:
      - url: https://api.quotable.io
    paths:
      /random:
        get:
          summary: Get random quote